[[build]]
  base = "."
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Optional: If you have Netlify Functions in a different directory
# [[build]]
#   functions = "path/to/your/functions" 